/*
 * Copyright (c) 2026 University Corporation for Atmospheric Research/Unidata
 * See LICENSE for license information.
 */

import com.github.jengelman.gradle.plugins.shadow.transformers.ApacheLicenseResourceTransformer
import com.github.jengelman.gradle.plugins.shadow.transformers.ApacheNoticeResourceTransformer
import com.github.jengelman.gradle.plugins.shadow.transformers.PropertiesFileTransformer
import java.nio.file.Paths
import java.security.MessageDigest
import java.text.SimpleDateFormat
import java.util.Date

plugins {
  id("java-base-conventions")
  alias(libs.plugins.shadow)
  alias(libs.plugins.cyclonedx.bom)
  application
}

extra["project.title"] = "THREDDS Data Manager (TDM)"

val downloadsDir = rootProject.layout.buildDirectory.dir("downloads").get()

dependencies {
  implementation(platform(project(":tds-platform")))

  implementation(project(":tdcommon"))

  implementation(libs.beust.jcommander)
  implementation(libs.guava)
  implementation(libs.httpcomponents.httpclient)
  implementation(libs.jdom2)
  implementation(libs.log4j.slf4j2Impl)
  implementation(libs.protobuf)
  implementation(libs.re2j)
  implementation(libs.slf4j.api)
  implementation(libs.springframework.beans)
  implementation(libs.springframework.context)
  implementation(libs.springframework.core)
  implementation(libs.ucar.cdmCore)
  implementation(libs.ucar.grib)
  implementation(libs.ucar.httpservices)

  testImplementation(project(":tds-test-utils"))

  testImplementation(libs.google.truth)
  testImplementation(libs.logback.classic)
  testImplementation(libs.ucar.cdmTestUtils)

  testCompileOnly(libs.junit4)

  testRuntimeOnly(libs.junit5.platformLauncher)
  testRuntimeOnly(libs.junit5.vintageEngine)
}

application { mainClass = "thredds.tdm.Tdm" }

tasks.jar { manifest { attributes["Main-Class"] = "thredds.tdm.Tdm" } }

val getBuildInfo =
  tasks.register<WriteProperties>("getBuildInfo") {
    destinationFile = getLayout().buildDirectory.file("resources/main/tdm.properties")
    comment = "Application configuration generated by Gradle"
    encoding = "UTF-8"
    property("tdm.version", project.version)
    val iso8601Format = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ")
    property("tdm.buildTimestamp", iso8601Format.format(Date()))
  }

tasks.processResources { finalizedBy(getBuildInfo) }

tasks.compileJava { dependsOn(getBuildInfo) }

tasks.shadowJar {
  duplicatesStrategy = DuplicatesStrategy.INCLUDE
  transform(ApacheLicenseResourceTransformer::class.java)
  transform(ApacheNoticeResourceTransformer::class.java)
  mergeServiceFiles()
  append("META-INF/spring.handlers")
  append("META-INF/spring.schemas")
  append("META-INF/spring.tooling")
  transform(PropertiesFileTransformer::class.java) {
    paths.add("META-INF/spring.factories")
    mergeStrategy.set(PropertiesFileTransformer.MergeStrategy.Append)
  }
  filesMatching("log4j2.xml") {
    duplicatesStrategy = DuplicatesStrategy.FAIL // Or WARN.
  }
  from(rootDir.absolutePath) {
    include("LICENSE")
    into("META-INF/unidata-license")
  }
  manifest { attributes["Main-Class"] = "thredds.tdm.Tdm" }
  destinationDirectory = downloadsDir
  archiveClassifier = ""
}

tasks.clean { delete(Paths.get(rootDir.absolutePath, "build", "downloads")) }

tasks.cyclonedxDirectBom {
  xmlOutput = downloadsDir.file("tdm-${project.version}-sbom.xml").asFile
  jsonOutput = downloadsDir.file("tdm-${project.version}-sbom.json").asFile
}

val createChecksums =
  tasks.register("createChecksums") {
    group = "build"
    description = "Create .sha1, .sha256, and .md5 checksum files for the uber-jars."

    doLast {
      listOf("MD5", "SHA-1", "SHA-256").forEach { algorithm ->
        fileTree(downloadsDir) { include("tdm-*.jar", "tdm-*.json", "tdm-*.xml") }
          .forEach { jarFile ->
            MessageDigest.getInstance(algorithm)
              .let { md ->
                md.digest(file(jarFile).readBytes()).let {
                  BigInteger(1, it).toString(16).padStart(md.digestLength * 2, '0')
                }
              }
              .let { checksum ->
                downloadsDir
                  .file("${jarFile.name}.${algorithm.lowercase().replace("-", "")}")
                  .asFile
                  .writeText(checksum)
              }
          }
      }
    }
    dependsOn(tasks.cyclonedxBom, tasks.shadowJar)
  }

tasks.assemble { dependsOn(tasks.cyclonedxBom, createChecksums) }

configurations.all {
  // exclude commons-logging
  // Standard Commons Logging discovery in action with spring-jcl (remove to avoid potential
  // conflicts)
  exclude(group = "commons-logging", module = "commons-logging")
}

configurations.testRuntimeOnly { exclude(group = "org.apache.logging.log4j") }
