on: [pull_request]

jobs:
  check-dependency-availability:
    name: Check fresh compile and assemble of TDS project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle (refresh dependencies)
        run: ./gradlew clean classes testClasses assemble --refresh-dependencies
