on:
  pull_request:
    paths:
      - 'docs/**'
      - 'gradle/**'

jobs:
  check-doc-build:
    name: TDS Documentation Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build docs using Gradle
        run: './gradlew :docs:build'
      - name: Upload a preview of the rendered html
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: documentation_${{ github.sha }}
          path: docs/build/site
