on:
  pull_request:
    paths:
      - 'docs/**'
      - 'gradle/**'

jobs:
  check-doc-build:
    name: TDS Documentation Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build docs using Gradle
        run: './gradlew :docs:build'
      - name: Upload a preview of the rendered html
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: documentation_${{ github.sha }}
          path: docs/build/site
