on: [pull_request]

jobs:
  tds-tests:
    name: TDS Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
        java-vendor: [ 'temurin' ]
        servletcontainer: [ 'tomcat10' ]
    steps:
      - uses: actions/checkout@v4
      - name: Build and test with Gradle (${{ matrix.java-vendor }} ${{ matrix.java-version }})
        uses: Unidata/thredds-test-action@v2
        with:
          java-vendor: ${{ matrix.java-vendor }}
          java-version: ${{ matrix.java-version }}
          build-tool: 'gradlew'
          test-command: '-Dtds.content.root.path=$CONTENT_DIR -Dtds.test.gretty.container=${{ matrix.servletcontainer }} --info --stacktrace testAll'
        env:
          CONTENT_DIR: ${{ github.workspace }}/tds/src/test/content
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: tds_JUnit_Results_${{ github.sha }}_AdoptOpenJDK-HS-${{ matrix.java }}-${{ matrix.servletcontainer }}
          path: build/reports/allTests

