on: [pull_request]

jobs:
  tds-tests:
    name: TDS Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest 11, 14 of zulu and 11 of temurin java
        java-version: [ 11 ]
        java-vendor: [ 'zulu', 'temurin' ]
        # test against tomcat 8.5.x, tomcat 9.x, and tomcat 10.x
        servletcontainer: [ 'tomcat85', 'tomcat9', 'tomcat10' ]
        include:
          - java-version: 14
            java-vendor: 'zulu'
            servletcontainer: 'tomcat85'
          - java-version: 14
            java-vendor: 'zulu'
            servletcontainer: 'tomcat9'
          - java-version: 14
            java-vendor: 'zulu'
            servletcontainer: 'tomcat10'
    steps:
      - uses: actions/checkout@v2
      - name: Build and test with Gradle (${{ matrix.java-vendor }} ${{ matrix.java-version }})
        uses: Unidata/thredds-test-action@v2
        with:
          java-vendor: ${{ matrix.java-vendor }}
          java-version: ${{ matrix.java-version }}
          build-tool: 'gradlew'
          test-command: '-Dtds.content.root.path=$CONTENT_DIR -Dtds.download.dir=$DOWNLOAD_DIR -Dtds.upload.dir=$UPLOAD_DIR -Dtds.test.gretty.container=${{ matrix.servletcontainer }} --info --stacktrace testAll'
        env:
          CONTENT_DIR: ${{ github.workspace }}/tds/src/test/content
          DOWNLOAD_DIR: '/tmp/download'
          UPLOAD_DIR: '/tmp/upload'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: tds_JUnit_Results_${{ github.sha }}_AdoptOpenJDK-HS-${{ matrix.java }}-matrix.servletcontainer }}
          path: build/reports/allTests

